AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambda-signUp-saveData

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  saveUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: signUp-saveData/
      Handler: handler/saveUserData.saveUserData
      Runtime: nodejs20.x
      Architectures:
      - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - handler/saveUserData.ts
    Policies:
      - AmazonDynamoDBFullAccess
      