version = 0.1

[default]
[default.global.parameters]
stack_name = "chatvious-app"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "chatvious-app"
region = "us-west-1"
# s3_bucket = "your-new-bucket-name"
parameter_overrides = "ChatviousCertificateArn=\"arn:aws:acm:us-west-1:580083607510:certificate/50b5027f-3ae1-491f-bd4e-b252cc2b953c\" ChatviousUsEastCertificateArn=\"arn:aws:acm:us-east-1:580083607510:certificate/51f9f2a0-a159-4bdc-8096-de519d8e7180\" ChatviousDomainHostedZoneId=\"Z0830272VPDW4QLTGOLN\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
