AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambda-signUp-saveData

Globals:
  Function:
    Environment:
      Variables:
        NODE_ENV: production
        CLIENT_ID: jet3kkqp4jnkm1v3ta7htu75g
        USER_POOL_ID: us-west-1_iJn1nk3N1
        # domain not set up yet
        DOMAIN: chatvious.coding-wielder.com/prod
    LoggingConfig:
      LogFormat: JSON

Resources:
  saveUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/cognito/post-signUp-trigger/
      Handler: saveUserData.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true

  dashboardPage:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Chatvious_dashboardPage
      Description: Renders dashboard Page for Chatvious
      PackageType: Image
      MemorySize: 256
      Timeout: 6
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: chatvious
      Policies:
        - AmazonDynamoDBReadOnlyAccess
      Events:
        ChatviousRestApiGETdashboard:
          Type: Api
          Properties:
            Path: /dashboard
            Method: GET
            RestApiId: !Ref ChatviousRestApi
    Metadata:
      DockerContext: ./src
      Dockerfile: dashboardPage.Dockerfile
      DockerTag: latest

  # exclude the callback route from authentication
  callback:
    Type: AWS::Serverless::Function
    Properties:
      Description: Callback route to exchange cognito auth codes for tokens
      FunctionName: Chatvious_callback
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 10
      PackageType: Image
      Environment:
        Variables:
          COGNITO_DOMAIN: https://chatvious.auth.us-west-1.amazoncognito.com
          CALLBACK_URL: http://localhost:3000/callback
      Events:
        ChatviousRestApiGETcallback:
          Type: Api
          Properties:
            Path: /callback
            Method: GET
            RestApiId: !Ref ChatviousRestApi
            Auth:
              Authorizer: NONE
    Metadata:
      DockerContext: ./src
      Dockerfile: callback.Dockerfile
      DockerTag: latest

  LambdaAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Chatvious_LambdaAuthorizer
      Description: The Lambda Authorizer for chatvious
      MemorySize: 128
      Timeout: 10
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          COGNITO_DOMAIN: https://chatvious.auth.us-west-1.amazoncognito.com
    Metadata:
      DockerContext: ./src
      Dockerfile: LambdaAuthorizer.Dockerfile
      DockerTag: latest

  ChatviousRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Chatvious_RestApi
      StageName: prod
      Auth:
        Authorizers:
          LambdaAuthorizer:
            FunctionArn: !GetAtt LambdaAuthorizer.Arn
            Identity:
              Header: Cookie
              ReauthorizeEvery: 0
        DefaultAuthorizer: LambdaAuthorizer
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /dashboard:
            get:
              x-amazon-apigateway-integration:
                httpMethod: GET
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${dashboardPage.Arn}/invocations
              responses: {}
          /callback:
            get:
              x-amazon-apigateway-integration:
                httpMethod: GET
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${callback.Arn}/invocations
              responses: {}
      # Below is the correct syntax. I don't know why it's erroring in VSCode.
      EndpointConfiguration: REGIONAL
      # Set up domain configuration once I get a domain
      Cors:
        MaxAge: 5