AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambda-signUp-saveData

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON

Resources:
  saveUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/cognito/post-signUp-trigger/
      Handler: saveUserData.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true

  dashboardPage:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Chatvious:dashboardPage
      Description: Renders dashboard Page for Chatvious
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          NODE_ENV: production
    Metadata:
      DockerContext: ./src
      Dockerfile: dashboardPage.Dockerfile
      DockerTag: latest