quarkus.lambda.handler=Authorizer
quarkus.index-dependency.smallrye-jwt.group-id=io.smallrye
quarkus.index-dependency.smallrye-jwt.artifact-id=smallrye-jwt
quarkus.ssl.native=true

# Manual JWT key handling
mp.jwt.verify.publickey.algorithm=EdDSA
mp.jwt.verify.issuer=chatvious
quarkus.log.level=ERROR

# SSM Parameter Store configuration
ssm.private.key.parameter=/chatvious/private_key
ssm.public.key.parameter=/chatvious/public_key
